version: '3'
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./html:/usr/share/nginx/html
      - ~/.ssh:/var/www/.ssh:ro
    #entrypoint: "php-fpm --nodaemonize"

